/**
 * FreemindFacts — DynamoDB seeder
 *
 * Creates the FreemindFacts table (+ GSIs) if absent, then populates it with
 * facts generated by Gemini 2.0 Flash (paid tier → 2000 RPM).
 *
 * Run locally:   npx ts-node scripts/seed-facts.ts
 * Run on Lambda: deploy this file, set handler to seed-facts.handler
 *
 * Required env vars:
 *   GEMINI_API_KEY   — Google AI Studio key (paid billing account)
 *   AWS_REGION       — default: us-east-1
 *   DYNAMODB_TABLE   — default: FreemindFacts
 *   SEED_CONCURRENCY — default: 15 (safe for 2000 RPM paid tier)
 */

import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { createHash } from "crypto";
import {
  DynamoDBClient,
  CreateTableCommand,
  DescribeTableCommand,
  ResourceNotFoundException,
  waitUntilTableExists,
  ProjectionType,
  BillingMode,
  ScalarAttributeType,
  KeyType,
} from "@aws-sdk/client-dynamodb";
import {
  DynamoDBDocumentClient,
  QueryCommand,
  BatchWriteCommand,
  UpdateCommand,
} from "@aws-sdk/lib-dynamodb";
import { GoogleGenerativeAI } from "@google/generative-ai";

// ── Config ─────────────────────────────────────────────────────────────────────

const TABLE_NAME      = process.env.DYNAMODB_TABLE   ?? "FreemindFacts";
const REGION          = process.env.AWS_REGION        ?? "us-east-1";
const GEMINI_KEY      = process.env.GEMINI_API_KEY    ?? "";
const CONCURRENCY     = parseInt(process.env.SEED_CONCURRENCY ?? "15");
const FACTS_PER_TOPIC = 50;
const GEMINI_MODEL    = "gemini-3.1-flash-lite";

// ── AWS clients ────────────────────────────────────────────────────────────────

const ddbClient = new DynamoDBClient({ region: REGION });
const doc = DynamoDBDocumentClient.from(ddbClient, {
  marshallOptions: { removeUndefinedValues: true },
});

// ── Gemini client ──────────────────────────────────────────────────────────────

const genAI = new GoogleGenerativeAI(GEMINI_KEY);
const gemini = genAI.getGenerativeModel({ model: GEMINI_MODEL });

// ── Full category + topic catalogue ───────────────────────────────────────────
// 18 categories · 310 total subtopics

const SEED_CATEGORIES: Record<string, string[]> = {
  Mythology: [
    "Krishna", "Shiva", "Vishnu", "Ganesha", "Brahma", "Durga", "Kali", "Hanuman",
    "Rama", "Lakshmi", "Zeus", "Poseidon", "Athena", "Apollo", "Hades", "Hercules",
    "Medusa", "Achilles", "Odin", "Thor", "Loki", "Freya", "Ragnarok",
    "Ra", "Osiris", "Isis", "Anubis", "Quetzalcoatl", "Aztec Sun God",
  ],
  "Space & Astronomy": [
    "Black Holes", "Neutron Stars", "The Big Bang", "Dark Matter", "Dark Energy",
    "Exoplanets", "The Sun", "The Moon", "Mars", "Jupiter", "Saturn", "Venus",
    "Milky Way", "Andromeda Galaxy", "Supernovas", "Wormholes",
    "NASA Missions", "James Webb Telescope", "International Space Station",
    "Comets & Asteroids", "The Oort Cloud", "Pulsars", "Quasars",
  ],
  Science: [
    "Quantum Physics", "Theory of Relativity", "Human DNA", "CRISPR Gene Editing",
    "Evolution", "Photosynthesis", "Ocean Currents", "Plate Tectonics", "Volcanoes",
    "Earthquakes", "Periodic Table", "Nuclear Fusion", "Lasers", "Superconductors",
    "Nanotechnology", "Stem Cells", "Viruses & Bacteria", "Climate Science",
    "Radioactivity", "Electromagnetism",
  ],
  History: [
    "Ancient Egypt", "Roman Empire", "Alexander the Great", "Genghis Khan",
    "The Mongol Empire", "World War I", "World War II", "The Cold War",
    "The Renaissance", "French Revolution", "The Industrial Revolution",
    "British Empire", "The Silk Road", "Ottoman Empire", "Ancient India Maurya",
    "Mughal Empire", "The Crusades", "The Black Death", "Age of Exploration",
    "American Civil War", "Russian Revolution",
  ],
  "Ancient Civilizations": [
    "Mesopotamia", "Sumerian Civilization", "Ancient Babylon",
    "Indus Valley Civilization", "Ancient Greece", "Minoan Civilization",
    "Carthage", "Phoenicians", "Ancient China Han Dynasty",
    "Ancient Persia Achaemenid", "Olmec Civilization", "Ancient Maya",
    "Aztec Empire", "Inca Empire", "Ancient Nubia",
  ],
  "Psychology & Mind": [
    "Cognitive Biases", "Confirmation Bias", "Dunning-Kruger Effect",
    "Impostor Syndrome", "Classical Conditioning", "Operant Conditioning",
    "Freudian Theory", "Jungian Archetypes", "Memory & Forgetting",
    "Sleep & Dreams", "Flow State", "Emotional Intelligence",
    "Motivation & Willpower", "Social Conformity", "Stockholm Syndrome",
    "Placebo Effect", "Body Language", "Persuasion & Influence", "Anxiety & Fear",
  ],
  "Philosophy & Wisdom": [
    "Stoicism", "Existentialism", "Absurdism", "Nihilism", "Utilitarianism",
    "Kantian Ethics", "Plato", "Aristotle", "Socrates",
    "Taoism", "Buddhism", "Confucianism", "Friedrich Nietzsche",
    "Arthur Schopenhauer", "René Descartes", "Free Will vs Determinism",
    "The Ship of Theseus", "Trolley Problem", "The Nature of Consciousness",
  ],
  "Health & Human Body": [
    "The Human Brain", "The Heart & Circulatory System", "The Immune System",
    "Gut Microbiome", "Human Skeleton", "Hormones & Endocrine System",
    "The Human Eye", "Sleep Science", "Nutrition & Metabolism",
    "Exercise & Muscles", "Cancer Biology", "Vaccines & Immunity",
    "Antibiotics", "The Nervous System", "Blood Types",
    "Genetics & Heredity", "Aging & Longevity",
  ],
  "Nature & Animals": [
    "Deep Sea Creatures", "Amazon Rainforest", "Arctic & Antarctic",
    "Coral Reefs", "Apex Predators", "Insects & Pollinators",
    "Migration Patterns", "Animal Intelligence", "Plant Defense Mechanisms",
    "Symbiosis & Mutualism", "Fungi & Mycelium", "Endangered Species",
    "Bioluminescence", "Camouflage in Nature", "Animal Communication",
    "Whales & Cetaceans", "Birds of Prey", "Venomous Animals",
  ],
  "Technology & Innovations": [
    "History of the Internet", "Artificial Intelligence", "Machine Learning",
    "Blockchain", "The Printing Press", "Steam Engine",
    "Electricity Tesla & Edison", "Telephone & Radio",
    "Semiconductors & Transistors", "Space Technology", "Robotics",
    "Quantum Computing", "Augmented & Virtual Reality", "Drones",
    "3D Printing", "Renewable Energy Solar", "Nuclear Energy", "Self-Driving Cars",
  ],
  "Mathematics & Numbers": [
    "Pi", "Fibonacci Sequence", "Prime Numbers", "Infinity & Cantor",
    "Golden Ratio", "Euler's Identity", "Pythagoras", "Fermat's Last Theorem",
    "The Riemann Hypothesis", "Game Theory", "Probability & Statistics",
    "Chaos Theory", "Fractals", "Zero History & Impact",
    "Cryptography & Codes", "Graph Theory", "Topology",
  ],
  "Art & Culture": [
    "Leonardo da Vinci", "Michelangelo", "Vincent van Gogh", "Pablo Picasso",
    "Frida Kahlo", "The Impressionist Movement", "Baroque Art",
    "The Louvre", "The Sistine Chapel", "Ancient Cave Paintings",
    "Classical Music Beethoven", "Classical Music Mozart", "Jazz Origins",
    "Rock & Roll History", "Hip-Hop Origins", "Ballet",
    "Traditional Indian Dance", "Japanese Kabuki",
  ],
  "World Facts & Geography": [
    "Extreme Geography Highest & Lowest", "Countries with No Army",
    "Micronations", "Unusual Border Facts", "World's Oldest Cities",
    "The Arctic vs Antarctic", "Flags & Their Meanings",
    "Languages Rarest & Most Spoken", "Food Origins",
    "Cultural Traditions Worldwide", "World Records Natural",
    "World Records Human", "Uninhabited Islands",
    "The Bermuda Triangle", "Underground Cities", "Cave Systems",
  ],
  "Famous Scientists & Inventors": [
    "Isaac Newton", "Albert Einstein", "Marie Curie", "Nikola Tesla",
    "Charles Darwin", "Galileo Galilei", "Stephen Hawking", "Alan Turing",
    "Ada Lovelace", "Rosalind Franklin", "Archimedes", "Thomas Edison",
    "Alexander Fleming", "Carl Sagan", "Richard Feynman",
    "Gregor Mendel", "Srinivasa Ramanujan", "C.V. Raman",
  ],
  "Economics & Business": [
    "The Great Depression", "The 2008 Financial Crisis",
    "How the Stock Market Works", "Capitalism vs Socialism",
    "Adam Smith & The Wealth of Nations", "John Maynard Keynes",
    "Warren Buffett", "Steve Jobs & Apple", "The Rise of Amazon",
    "Bitcoin & Cryptocurrency", "Inflation & Deflation",
    "Monopolies in History", "The Tulip Mania", "Behavioral Economics",
  ],
  "Food & Cuisine": [
    "Origins of Bread", "History of Spices & The Spice Trade",
    "Fermentation Science", "How Chocolate Was Discovered",
    "History of Coffee", "Tea & Its Origins",
    "Street Food Around the World", "Why Food Goes Bad",
    "The Science of Taste", "The Maillard Reaction",
    "Umami The Fifth Taste", "History of Salt", "How Wine Is Made",
    "Food Preservation Methods", "History of Sugar",
  ],
  "Life Hacks & Productivity": [
    "The Pomodoro Technique", "Deep Work", "Habit Loops",
    "Memory Palaces & Mnemonics", "Speed Reading", "The Feynman Technique",
    "Parkinson's Law", "Pareto Principle 80 20 Rule",
    "The Power of Journaling", "Cold Exposure Benefits",
    "Intermittent Fasting Science", "Meditation & the Brain",
    "Power Napping", "The Two-Minute Rule", "Digital Minimalism",
    "Ikigai Japanese Purpose", "The Science of Habit Formation",
  ],
  "Language & Words": [
    "Origin of English", "How Languages Evolve & Die", "Sign Languages",
    "Oldest Written Languages", "Sanskrit & Its Influence",
    "Latin & Its Legacy", "The Rosetta Stone",
    "Words with No English Translation", "False Cognates",
    "The Sapir-Whorf Hypothesis", "Pidgin & Creole Languages",
    "Constructed Languages Esperanto", "How Children Acquire Language",
    "Animal Communication vs Language", "The Most Complex Writing Systems",
  ],
};

// ── Utility: SHA-256 hash ──────────────────────────────────────────────────────

function sha256(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

// ── Utility: simple semaphore for capped concurrency ──────────────────────────

class Semaphore {
  private slots: number;
  private queue: Array<() => void> = [];

  constructor(max: number) { this.slots = max; }

  acquire(): Promise<void> {
    if (this.slots > 0) { this.slots--; return Promise.resolve(); }
    return new Promise(resolve => this.queue.push(resolve));
  }

  release(): void {
    const next = this.queue.shift();
    if (next) { next(); } else { this.slots++; }
  }
}

// ── Phase 1: ensure DynamoDB table exists ──────────────────────────────────────

async function ensureTable(): Promise<void> {
  try {
    await ddbClient.send(new DescribeTableCommand({ TableName: TABLE_NAME }));
    console.log(`[seed] Table "${TABLE_NAME}" already exists — skipping creation.`);
    return;
  } catch (err) {
    if (!(err instanceof ResourceNotFoundException)) throw err;
  }

  console.log(`[seed] Creating table "${TABLE_NAME}" ...`);
  await ddbClient.send(new CreateTableCommand({
    TableName: TABLE_NAME,
    BillingMode: BillingMode.PAY_PER_REQUEST,
    AttributeDefinitions: [
      { AttributeName: "PK",          AttributeType: ScalarAttributeType.S },
      { AttributeName: "SK",          AttributeType: ScalarAttributeType.S },
      { AttributeName: "category",    AttributeType: ScalarAttributeType.S },
      { AttributeName: "shard",       AttributeType: ScalarAttributeType.N },
      { AttributeName: "contentHash", AttributeType: ScalarAttributeType.S },
      { AttributeName: "createdAt",   AttributeType: ScalarAttributeType.S },
    ],
    KeySchema: [
      { AttributeName: "PK", KeyType: KeyType.HASH  },
      { AttributeName: "SK", KeyType: KeyType.RANGE },
    ],
    GlobalSecondaryIndexes: [
      {
        IndexName:  "CategoryShardIndex",
        KeySchema: [
          { AttributeName: "category", KeyType: KeyType.HASH  },
          { AttributeName: "shard",    KeyType: KeyType.RANGE },
        ],
        Projection: { ProjectionType: ProjectionType.ALL },
      },
      {
        IndexName:  "ContentHashIndex",
        KeySchema: [
          { AttributeName: "contentHash", KeyType: KeyType.HASH  },
          { AttributeName: "createdAt",   KeyType: KeyType.RANGE },
        ],
        Projection: { ProjectionType: ProjectionType.KEYS_ONLY },
      },
    ],
  }));

  await waitUntilTableExists(
    { client: ddbClient, maxWaitTime: 120 },
    { TableName: TABLE_NAME },
  );
  console.log(`[seed] Table "${TABLE_NAME}" is ACTIVE.`);
}

// ── Phase 2: call Gemini, return raw fact strings ──────────────────────────────

async function fetchFacts(category: string, topic: string): Promise<string[]> {
  const prompt = `You are a factual knowledge database. Generate exactly ${FACTS_PER_TOPIC} unique, surprising, and educational facts about "${topic}" in the category "${category}".

Rules:
- Each fact must be a single sentence, maximum 280 characters
- Facts must be accurate, verifiable, and genuinely interesting
- No repetition between facts
- No bullet points, numbering, markdown, or any formatting
- Return ONLY a valid JSON array of strings — no text before or after
- Example format: ["Fact one.", "Fact two.", ...]`;

  const maxRetries = 4;
  let delay = 2000;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const result = await gemini.generateContent(prompt);
      const text   = result.response.text().trim();

      // Strip markdown fences if Gemini wraps the JSON
      const clean = text
        .replace(/^```(?:json)?\s*/i, "")
        .replace(/\s*```\s*$/, "")
        .trim();

      const facts: unknown = JSON.parse(clean);

      if (
        !Array.isArray(facts) ||
        !facts.every(f => typeof f === "string" && f.length > 0)
      ) {
        throw new Error("Gemini response is not a string[]");
      }

      return (facts as string[]).filter(f => f.trim().length > 0);
    } catch (err: unknown) {
      const isRateLimit =
        String(err).includes("429") ||
        String(err).includes("RESOURCE_EXHAUSTED") ||
        String(err).includes("quota");

      if (attempt === maxRetries) {
        console.error(`[seed] Gemini failed after ${maxRetries} retries for ${category}/${topic}:`, err);
        return [];
      }

      const waitMs = isRateLimit ? delay : 1000;
      console.warn(`[seed] Gemini error (attempt ${attempt}/${maxRetries}) for ${category}/${topic} — retrying in ${waitMs}ms`);
      await new Promise(r => setTimeout(r, waitMs));
      delay = Math.min(delay * 2, 60_000);
    }
  }

  return [];
}

// ── Phase 3: dedup check via GSI-2 (ContentHashIndex) ────────────────────────
// Checks all hashes in parallel — one Query per hash, batched to 25 at a time.

async function filterDuplicates(facts: string[]): Promise<string[]> {
  const results = await Promise.all(
    facts.map(async (fact) => {
      const hash = sha256(fact.trim().toLowerCase());
      const res  = await doc.send(new QueryCommand({
        TableName:              TABLE_NAME,
        IndexName:              "ContentHashIndex",
        KeyConditionExpression: "contentHash = :h",
        ExpressionAttributeValues: { ":h": hash },
        Limit: 1,
        Select: "COUNT",
      }));
      return res.Count === 0 ? fact : null;
    }),
  );
  return results.filter((f): f is string => f !== null);
}

// ── Phase 4: DynamoDB BatchWriteItem with unprocessed-item retry ──────────────

async function batchWrite(items: Record<string, unknown>[]): Promise<void> {
  const CHUNK = 25; // DynamoDB hard limit per BatchWriteItem call
  for (let i = 0; i < items.length; i += CHUNK) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let chunk: any[] = items.slice(i, i + CHUNK).map(Item => ({ PutRequest: { Item } }));

    let attempt = 0;
    while (chunk.length > 0 && attempt < 5) {
      const res = await doc.send(new BatchWriteCommand({
        RequestItems: { [TABLE_NAME]: chunk },
      }));

      const unprocessed = res.UnprocessedItems?.[TABLE_NAME];
      if (!unprocessed || unprocessed.length === 0) break;

      // Back off before retrying unprocessed items (table throttled)
      chunk = unprocessed;
      attempt++;
      await new Promise(r => setTimeout(r, 200 * Math.pow(2, attempt)));
    }

    if (attempt === 5) {
      console.error(`[seed] BatchWrite: some items could not be written after 5 retries`);
    }
  }
}

// ── Phase 5: update META stats row ────────────────────────────────────────────

async function updateMeta(category: string, addedCount: number): Promise<void> {
  await doc.send(new UpdateCommand({
    TableName: TABLE_NAME,
    Key: { PK: `META#${category}`, SK: "STATS" },
    UpdateExpression:
      "SET lastSeeded = :ts ADD totalFacts :n",
    ExpressionAttributeValues: {
      ":ts": new Date().toISOString(),
      ":n":  addedCount,
    },
  }));
}

// ── Orchestrate one topic ──────────────────────────────────────────────────────

async function seedTopic(category: string, topic: string): Promise<number> {
  const rawFacts = await fetchFacts(category, topic);
  if (rawFacts.length === 0) return 0;

  const newFacts  = await filterDuplicates(rawFacts);
  if (newFacts.length === 0) {
    console.log(`[seed] ${category}/${topic} — all ${rawFacts.length} facts already exist`);
    return 0;
  }

  const createdAt = new Date().toISOString();
  const items = newFacts.map((fact) => {
    const factId      = crypto.randomUUID();
    const contentHash = sha256(fact.trim().toLowerCase());
    const shard       = Math.floor(Math.random() * 10); // 0-9

    return {
      PK:          `CATEGORY#${category}`,
      SK:          `FACT#${factId}`,
      factId,
      category,
      topic,
      fact,
      contentHash,
      shard,
      createdAt,
      status:  "active",
      source:  GEMINI_MODEL,
    };
  });

  await batchWrite(items);
  console.log(
    `[seed] ${category}/${topic} — wrote ${items.length} facts` +
    (rawFacts.length > newFacts.length
      ? ` (${rawFacts.length - newFacts.length} duplicates skipped)`
      : ""),
  );
  return items.length;
}

// ── Main orchestrator ──────────────────────────────────────────────────────────

interface SeedEvent {
  // Optional: seed only specific categories (useful for re-runs / repairs)
  categories?: string[];
}

export async function handler(event: SeedEvent = {}): Promise<object> {
  if (!GEMINI_KEY) throw new Error("GEMINI_API_KEY env var is not set");

  const startMs = Date.now();
  await ensureTable();

  // Build flat list of [category, topic] pairs
  const targetCategories = event.categories?.length
    ? event.categories
    : Object.keys(SEED_CATEGORIES);

  const pairs: Array<[string, string]> = targetCategories.flatMap(cat =>
    (SEED_CATEGORIES[cat] ?? []).map(topic => [cat, topic] as [string, string]),
  );

  console.log(`[seed] Starting: ${pairs.length} topics across ${targetCategories.length} categories`);
  console.log(`[seed] Concurrency: ${CONCURRENCY} parallel Gemini calls`);

  // Track per-category totals for META update
  const categoryTotals: Record<string, number> = {};
  const sem = new Semaphore(CONCURRENCY);
  let completed = 0;

  await Promise.all(
    pairs.map(async ([category, topic]) => {
      await sem.acquire();
      try {
        const added = await seedTopic(category, topic);
        categoryTotals[category] = (categoryTotals[category] ?? 0) + added;
      } finally {
        sem.release();
        completed++;
        if (completed % 25 === 0) {
          console.log(`[seed] Progress: ${completed}/${pairs.length} topics done`);
        }
      }
    }),
  );

  // Update META stats for each category
  await Promise.all(
    Object.entries(categoryTotals).map(([cat, count]) => updateMeta(cat, count)),
  );

  const totalAdded = Object.values(categoryTotals).reduce((s, n) => s + n, 0);
  const elapsed    = ((Date.now() - startMs) / 1000).toFixed(1);

  const summary = {
    ok:          true,
    topicsSeeded: pairs.length,
    factsAdded:  totalAdded,
    elapsedSec:  parseFloat(elapsed),
    breakdown:   categoryTotals,
  };

  console.log("[seed] Done:", JSON.stringify(summary, null, 2));
  return summary;
}

// ── Run directly (ts-node / node) ─────────────────────────────────────────────

const isDirectRun = process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/seed-facts.ts") ||
                    process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/seed-facts.js");

if (isDirectRun) {
  const categories = process.argv.slice(2); // e.g. npx tsx scripts/seed-facts.ts Mythology Science
  handler(categories.length ? { categories } : {})
    .then(() => process.exit(0))
    .catch(err => { console.error(err); process.exit(1); });
}
